# Generated by Django 6.1 on 2026-08-31 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('follow_ups', '0001_initial'),
        ('patients', '0002_patient_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('follow_up_reminder', 'Follow-Up Reminder'), ('system', 'System')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='patients.patient')),
                ('related_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='appointments.appointment')),
                ('related_follow_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='follow_ups.followup')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'read'], name='notificatio_patient_793054_idx')],
            },
        ),
    ]
