# Generated by Django 6.1.1 on 2026-09-16 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0006_conversation_consecutive_agent_failures_and_more'),
        ('patients', '0002_patient_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('patient_request', 'Patient Request'), ('out_of_scope', 'Out of Scope'), ('repeated_failure', 'Repeated Failure'), ('safety_review', 'Safety Review'), ('administrative_issue', 'Administrative Issue'), ('human_assistance_required', 'Human Assistance Required')], max_length=32)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High')], default='normal', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_escalations', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='conversations.conversation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='patients.patient')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscalationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('status_changed', 'Status Changed'), ('staff_response_sent', 'Staff Response Sent'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_events', to=settings.AUTH_USER_MODEL)),
                ('escalation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='escalations.escalation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='escalation',
            index=models.Index(fields=['status', 'priority'], name='escalations_status_b50ec0_idx'),
        ),
    ]
