# Generated by Django 6.1.1 on 2026-09-16 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0006_conversation_consecutive_agent_failures_and_more'),
        ('patients', '0002_patient_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('escalated', 'Escalated')], default='running', max_length=16)),
                ('final_agent', models.CharField(blank=True, default='', max_length=32)),
                ('error_type', models.CharField(blank=True, choices=[('llm_error', 'LLM Error'), ('tool_error', 'Tool Error'), ('database_error', 'Database Error'), ('validation_error', 'Validation Error'), ('authorization_error', 'Authorization Error'), ('retrieval_error', 'Retrieval Error'), ('safety_error', 'Safety Error'), ('timeout', 'Timeout'), ('unknown_error', 'Unknown Error')], default='', max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_traces', to='conversations.conversation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_traces', to='patients.patient')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentTraceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.PositiveIntegerField()),
                ('component', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='running', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='observability.agenttrace')),
            ],
            options={
                'ordering': ['trace_id', 'step_index'],
            },
        ),
        migrations.AddIndex(
            model_name='agenttrace',
            index=models.Index(fields=['patient', 'started_at'], name='observabili_patient_40c059_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttrace',
            index=models.Index(fields=['status'], name='observabili_status_dd8dfb_idx'),
        ),
        migrations.AddConstraint(
            model_name='agenttracestep',
            constraint=models.UniqueConstraint(fields=('trace', 'step_index'), name='unique_step_index_per_trace'),
        ),
    ]
