# Generated by Django 6.1 on 2026-08-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('cardiac_respiratory', 'Cardiac / Respiratory'), ('neurological', 'Neurological'), ('bleeding_trauma', 'Bleeding / Trauma'), ('mental_health_crisis', 'Mental Health Crisis'), ('allergic_reaction', 'Allergic Reaction'), ('general', 'General')], default='general', max_length=32)),
                ('trigger', models.TextField(help_text='Regex pattern matched against the raw patient message.')),
                ('severity', models.CharField(choices=[('emergency', 'Emergency'), ('urgent', 'Urgent'), ('routine', 'Routine'), ('informational', 'Informational')], max_length=16)),
                ('response', models.TextField(help_text='Fixed response shown to the patient when this rule is the deciding match.')),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-severity', 'name'],
            },
        ),
    ]
