# Generated by Django 6.1 on 2026-08-27 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('source', models.CharField(help_text='Human-readable name of the source, e.g. publisher.', max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('general_health', 'General Health'), ('symptoms', 'Symptoms'), ('diagnostic_tests', 'Diagnostic Tests'), ('preventive_care', 'Preventive Care'), ('common_procedures', 'Common Procedures'), ('healthcare_services', 'Healthcare Services')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('chunk_index', models.PositiveIntegerField()),
                ('embedding', models.JSONField(help_text='List of floats produced by knowledge/embeddings.py')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.healthcaredocument')),
            ],
            options={
                'ordering': ['document_id', 'chunk_index'],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_chunk_index_per_document')],
            },
        ),
    ]
