# Generated by Django 6.1 on 2026-08-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Rolling, non-clinical summary of the conversation used as LLM context. Never contains diagnoses or medical assumptions — see agents/navigator/prompts.py.'),
        ),
    ]
