# Generated by Django 6.1 on 2026-08-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_message_sources_message_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='appointment_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='pending_action',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
