# Generated by Django 6.1 on 2026-08-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_message_appointment_data_message_pending_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='follow_up_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
