# Generated by Django 6.1 on 2026-08-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
