# Generated by Django 6.1 on 2026-08-31 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('conversations', '0005_message_follow_up_data'),
        ('patients', '0002_patient_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High')], default='normal', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='appointments.appointment')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='conversations.conversation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='patients.patient')),
            ],
            options={
                'ordering': ['due_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='scheduled', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follow_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='follow_ups.followup')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['patient', 'status'], name='follow_ups__patient_4131dd_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['status', 'scheduled_for'], name='follow_ups__status_cbe27e_idx'),
        ),
    ]
